name: 'moon - CI run reports'
author: 'Miles Johnson'
description: 'Reports the run results of `moon ci` to a pull request.'
inputs:
  access-token:
    description: 'GitHub access token to post comments.'
    required: true
  limit:
    description: 'Maximum number of actions to display in the report table.'
    default: 20
  matrix:
    description: 'Metadata about the current job matrix in JSON.'
    default: ''
  slow-threshold:
    description: 'Number of seconds before an action is to be considered slow.'
    default: 120
  sort-by:
    description: 'Field to sort actions by. Accepts "time" or "label".'
    default: ''
  sort-dir:
    description: 'Direction to sort with.'
    default: 'desc'
  workspace-root:
    description: 'Root of the moon workspace. Defaults to working directory.'
    default: ''
outputs:
  comment-created:
    description: 'Whether or not the comment was created on the pull request.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'moon'
  color: 'purple'
